### ISSUE TITLE
Change folders' names

### ISSUE THREAD

**Issue by kakiii** [DylanLIiii/XJTLU-manual#1]
It's not quite readable for me to understand these folders. I'll suggest going with Chinese characters or just using English instead. Naming folders with Pinyin is not quite ideal in projects.

**Comment by DylanLIiii** [comment]
Since this repo is automatically created by Gitbook Bot, even if the file name is changed in the repo, it will be synchronized into pinyin due to Gitbook Change, unless the name of the Group in the Gitbook is modified. There will be a change in the file hierarchy after the number of articles increases. consider setting it to English to solve this problem. I will also look for a better solution.
